# Docker Compose file for Divinimity development environment.

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4321:4321" # Astro dev server
    environment:
      - NODE_ENV=development
      # Public here means it is passed to the browser by Astro / Vite
      - PUBLIC_BACKEND_URL=http://localhost:3000
      - PUBLIC_URL=http://localhost:4321
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./backend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - RETHINKDB_HOST=db
      - RETHINKDB_PORT=28015
      - PUBLIC_BACKEND_URL=http://localhost:3000
      - PUBLIC_URL=http://localhost:4321
    depends_on:
      - db

  db:
    image: rethinkdb:latest
    ports:
      - "8081:8080" # Admin UI
      - "28015:28015"
    volumes:
      - rethinkdb_data:/data

volumes:
  rethinkdb_data:
