FROM node:24-trixie
WORKDIR /app

COPY . .

# Build shared first
WORKDIR /app/shared
RUN npm install -g typescript
RUN tsc -b


# Set working directory to frontend
WORKDIR /app/frontend
RUN npm install
EXPOSE 4321
CMD ["npm", "run", "dev"]
