FROM node:24-trixie
WORKDIR /app

# Copy manifests and tsconfigs for dependency installation
COPY backend/package*.json ./backend/
COPY backend/tsconfig.json ./backend/
COPY shared/tsconfig.json ./shared/


# Ensure dev deps are installed
ENV NODE_ENV=development

WORKDIR /app/backend
RUN npm install


# Copy the rest of the repo
WORKDIR /app
COPY  . .

# Build shared first
WORKDIR /app/shared
RUN npm install -g typescript
RUN tsc -b


WORKDIR /app/backend
EXPOSE 3000
CMD ["npm", "run", "dev"]
